services:
  netflix-notifier:
    build: .
    container_name: bouba_discord_netflix_notifier
    
    # Variables d'environnement depuis le fichier .env
    env_file:
      - .env
 # Définir le fuseau horaire
    environment:
      - TZ=Europe/Paris    
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro  # Synchroniser avec l'hôte (optionnel)    
    restart: unless-stopped
